# ~/.config/fuzzel/fuzzel.ini — rendered by sy
font=JetBrainsMono Nerd Font:size=12
dpi-aware=yes
prompt=$
icon-theme=Adwaita
icons-enabled=no
fields=name,generic,comment,categories,filename,keywords
terminal=foot
lines=12
width=40
tabs=4
horizontal-pad=16
vertical-pad=10
inner-pad=6
line-height=20

[colors]
background={{ colors.bg | replace("#", "") }}f0
text={{ colors.fg | replace("#", "") }}ff
match={{ colors.orange | replace("#", "") }}ff
selection={{ colors.bg1 | replace("#", "") }}ff
selection-text={{ colors.fg | replace("#", "") }}ff
selection-match={{ colors.yellow | replace("#", "") }}ff
border={{ ui.accent | replace("#", "") }}ff
prompt={{ ui.accent | replace("#", "") }}ff
input={{ colors.fg | replace("#", "") }}ff

[border]
width=2
radius=0

[dmenu]
exit-immediately-if-empty=yes
