//! `power::forecast` — sub-millisecond GRU forecaster running on CPU
//! via `tract`. Per `specs/research/sy-power/SPEC.md` §2 ("Why GRU on
//! CPU via tract, not NPU") and §3 ("`forecast::predict` via tract"),
//! the 1 Hz daemon tick consults this module to project the user's
//! activity class over the next 30-120 s, and the bandit then picks
//! the matching power profile.
//!
//! Step 24 (current) ships:
//!
//! - [`Model`]: a hot-reloadable wrapper around a runnable tract
//!   `TypedRunnableModel<TypedModel>`. The daemon (Step 26) holds it
//!   inside an `ArcSwap<Model>` so the trainer (Step 25) can swap a
//!   freshly-exported ONNX in without taking a lock on the read path.
//! - [`gru::infer`]: the inference entry point — takes a `&Model` and
//!   a feature window and returns a [`Forecast`].
//! - A shipped warmup ONNX under `fixtures/warmup.onnx`, generated by
//!   `examples/gen_warmup_gru.rs` and validated for byte-stability by
//!   `tests/forecast_reproducibility.rs`. The warmup model emits
//!   uniform probabilities across the five activity classes — the
//!   rules-baseline floor used during the 14-day onboarding gate
//!   (Step 26).

pub mod gru;
pub mod model;

pub use model::Model;

/// One forecast over the configured horizon. Per SPEC §3 ("forecast
/// schema"), the bandit consumes the class-probability vector as its
/// context arm; the audit log (Step 23) snapshots the full struct so
/// `sy power explain` can replay decisions verbatim.
#[derive(Debug, Clone, PartialEq)]
pub struct Forecast {
    /// Projection horizon in seconds. Pinned at construction time to
    /// the model's training horizon — the warmup model emits a default
    /// (90 s, the SPEC §2 midpoint of "30-120 s").
    pub horizon_s: u32,
    /// `(class_name, probability)` pairs in
    /// [`crate::power::forecast::model::ACTIVITY_CLASSES`] order.
    /// Probabilities sum to ~1.0; floating-point error tolerated.
    pub class_probs: Vec<(String, f32)>,
}
